<a href="https://colab.research.google.com/github/illuly/Python/blob/main/%EC%98%A4%EC%B0%A8%ED%96%89%EB%A0%AC1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
from google.colab import files

with open('example.txt', 'w') as f:
  f.write('some content')

files.download('example.txt')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [8]:
!pip install cartopy
import cartopy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 30.5 MB/s eta 0:00:00


In [7]:
!apt-get -qq install -y graphviz && pip install pydot
import pydot

In [15]:
pip cache purge


Files removed: 6


In [16]:
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode

def take_photo(filename='photo.jpg', quality=0.8):
  js = Javascript('''
    async function takePhoto(quality) {
      const div = document.createElement('div');
      const capture = document.createElement('button');
      capture.textContent = 'Capture';
      div.appendChild(capture);

      const video = document.createElement('video');
      video.style.display = 'block';
      const stream = await navigator.mediaDevices.getUserMedia({video: true});

      document.body.appendChild(div);
      div.appendChild(video);
      video.srcObject = stream;
      await video.play();

      // Resize the output to fit the video element.
      google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);

      // Wait for Capture to be clicked.
      await new Promise((resolve) => capture.onclick = resolve);

      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);
      stream.getVideoTracks()[0].stop();
      div.remove();
      return canvas.toDataURL('image/jpeg', quality);
    }
    ''')
  display(js)
  data = eval_js('takePhoto({})'.format(quality))
  binary = b64decode(data.split(',')[1])
  with open(filename, 'wb') as f:
    f.write(binary)
  return filename

In [ ]:
from IPython.display import Image
try:
  filename = take_photo()
  print('Saved to {}'.format(filename))

  # Show the image which was just taken.
  display(Image(filename))
except Exception as err:
  # Errors will be thrown if the user does not have a webcam or if they do not
  # grant the page permission to access it.
  print(str(err))

In [4]:
!pip install matplotlib-venn

In [73]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [27]:
import pandas as pd

In [57]:
#null 처리 함수
def fillna(df):
  df['Age'].fillna(df['Age'].mean(), inplace = True)
  df['Cabin'].fillna('N', inplace = True)
  df['Embarked'].fillna('N', inplace = True)
  df['Fare'].fillna(0, inplace = True)
  return df

In [45]:
#알고리즘 불필요한 피쳐 제거
def drop_feature(df):
  df.drop(['PassengerId', 'Name', 'Ticket'], axis = 1, inplace = True)
  return df

In [66]:
# 레이블 인코딩 수행
from sklearn.preprocessing import LabelEncoder
def format_feature(df):
  df['Cabin'] = df['Cabin'].str[::1]
  features = ['Cabin','Sex', 'Embarked']
  for feature in features:
    le = LabelEncoder()
    le = le.fit(df[feature])
    df[feature] = le.transform(df[feature])
  return df

In [63]:
# 데이터 전처리 함수 호출
def transform_features(df):
  df = fillna(df)
  df = drop_feature(df)
  df = format_feature(df)
  return df

In [173]:
def get_clf_eval(y_test, pred):
  confusion = confusion_matrix(y_test, pred)
  accuracy = accuracy_score(y_test, pred)
  precision = precision_score(y_test, pred)
  recall = recall_score(y_test, pred)
  #f1 score 추가
  f1 = f1_score(y_test,pred)

  print('오차행렬')
  print(confusion)
  print('정확도 : {0:4f}, 정밀도 : {0:4f}, 재현율 : {2:4f}, f1: {3:4f}'. format(accuracy, precision, recall, f1))

  thresholds = [0.4,0.45,0.5,0.55,0.6]
  pred_proba =lr_clf.predict_proba(x_test)
  get_eval_by_thresholds(y_test, pred_proba[:,1].reshape(-1,1), thresholds)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

titanic_df = pd.read_csv("https://raw.githubusercontent.com/wikibook/pymlrev2/main/1%EC%9E%A5/titanic_train.csv")
y_titanic_df = titanic_df['Survived']
x_titanic_df = titanic_df.drop('Survived', axis = 1)
x_titanic_df = transform_features(x_titanic_df)

x_train, x_test, y_train, y_test = train_test_split(x_titanic_df, y_titanic_df, test_size = 0.20, random_state=11)

lr_clf = LogisticRegression(solver= 'liblinear')

lr_clf.fit(x_train, y_train)
pred = lr_clf.predict(x_test)
get_clf_eval(y_test, pred)

In [ ]:
pred_proba = lr_clf.predict_proba(x_test)
pred = lr_clf.predict(x_test)
print('pred_proba() 결과 shape : {0}'.format(pred_proba.shape))
print('pred_proba array에서 앞 3개 샘플 추출:\n:', pred_proba[:3])

In [ ]:
y_train

In [ ]:
x_test

In [ ]:
y_test

In [100]:
from sklearn.preprocessing import Binarizer
x = [[1,-1,2],
     [2,0,0],
     [0,1.1,1.2]]

binarizers = Binarizer(threshold = 1.1)

print(binarizers.fit_transform(x))

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [125]:
import numpy as np
custom_predict = binarizer.transform(pred_proba1)
custom_predict
uniques = np.unique(custom_predict)
len(uniques)


1

In [ ]:
from sklearn.preprocessing import Binarizer
custom_threshold = 0.5

pred_proba_1 = pred_proba[:,1].reshape(-1,1)

binarizer = Binarizer(threshold=custom_threshold).fit(pred_proba_1)
custom_predict = binarizer.transform(pred_proba_1)

get_clf_eval(y_test, custom_predict)

In [ ]:
from sklearn.preprocessing import Binarizer
custom_threshold = 0.3

pred_proba_1 = pred_proba[:,1].reshape(-1,1)

binarizer = Binarizer(threshold=custom_threshold).fit(pred_proba_1)
custom_predict = binarizer.transform(pred_proba_1)

get_clf_eval(y_test, custom_predict)

In [ ]:
thresholds = [0.4,0.45,0.5,0.55,0.6]

def get_eval_by_thresholds(y_test, pred_proba_c1, thresholds):
  for custom_threshold in thresholds:
    binarizer = Binarizer(threshold = custom_threshold).fit(pred_proba_c1)
    custom_predict = binarizer.transform(pred_proba_c1)
    #print('임계값', custom_predict)
    get_clf_eval(y_test, custom_predict)

get_eval_by_thresholds(y_test, pred_proba[:,1].reshape(-1,1), thresholds)


In [163]:
from sklearn.metrics import precision_recall_curve

pred_proba_class1 = lr_clf.predict_proba(x_test)[:,1]

precisions, recalls, thresholds = precision_recall_curve(y_test, pred_proba_class1)
print('반환된 분류 결정 임계값 배열 범위', thresholds.shape)

thr_index = np.arange(0, thresholds.shape[0], 15)
print('반환된 분류 결정 임계값 배열 index 10개', thr_index)
print('샘플용 10개 임계값',np.round(thresholds[thr_index],2))

print('임계값 별 정밀도',np.round(precisions[thr_index],3))
print('임계값 별 재현율',np.round(recalls[thr_index],3))


반환된 분류 결정 임계값 배열 범위 (165,)
반환된 분류 결정 임계값 배열 index 10개 [  0  15  30  45  60  75  90 105 120 135 150]
샘플용 10개 임계값 [0.02 0.11 0.13 0.14 0.17 0.25 0.32 0.44 0.61 0.73 0.87]
임계값 별 정밀도 [0.341 0.372 0.401 0.44  0.505 0.598 0.688 0.774 0.915 0.968 1.   ]
임계값 별 재현율 [1.    1.    0.967 0.902 0.902 0.902 0.869 0.787 0.705 0.492 0.262]


In [169]:
from sklearn.metrics import f1_score

f1 = f1_score(y_test, pred)
f1

0.7758620689655172